apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: student

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: ghcr.io/avhad-enterprises/student-marketplace-backend
  newName: ghcr.io/avhad-enterprises/student-marketplace-backend
  newTag: v20
